In [2]:
import torch
import numpy as np

In [3]:
#from list to tensor
data = [[1,2],[3,4]]
tensor = torch.tensor(data)

In [4]:
tensor

tensor([[1, 2],
        [3, 4]])

In [7]:
#from numpy to tensor
np_array = np.array(data)
tensor = torch.from_numpy(np_array)
tensor

tensor([[1, 2],
        [3, 4]])

In [11]:
x_ones = torch.ones(tensor.shape)
x_ones

tensor([[1., 1.],
        [1., 1.]])

In [12]:
tensor.shape

torch.Size([2, 2])

In [13]:
torch.ones_like(tensor)

tensor([[1, 1],
        [1, 1]])

In [14]:
x_rand = torch.rand_like(tensor, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Random Tensor: 
 tensor([[0.7377, 0.9362],
        [0.9530, 0.2998]]) 



In [15]:
shape =(3,3)
torch.ones(shape)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [16]:
torch.zeros(shape)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [17]:
torch.randn(shape)

tensor([[-0.8076, -0.2042,  0.0233],
        [ 1.6456, -0.7160, -0.4176],
        [-1.2904, -1.3461, -0.3066]])

###Attributes of a Tensor: Shape, Type, Device ###

In [18]:
tensor.shape

torch.Size([2, 2])

In [19]:
tensor.device

device(type='cpu')

In [22]:
tensor.dtype

torch.int64

In [23]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [24]:
tensor[0]

tensor([1, 2])

In [25]:
tensor[0][1]

tensor(2)

In [26]:
tensor[:,0]

tensor([1, 3])

In [27]:
tensor

tensor([[1, 2],
        [3, 4]])

In [29]:
#join tensors:
torch.cat([tensor, tensor, tensor], axis = 1)

tensor([[1, 2, 1, 2, 1, 2],
        [3, 4, 3, 4, 3, 4]])

In [30]:
#operations:
tensor@tensor

tensor([[ 7, 10],
        [15, 22]])

In [31]:
tensor.matmul(tensor)

tensor([[ 7, 10],
        [15, 22]])

In [35]:
t2 = torch.rand_like(torch.ones(3,3))
t2

tensor([[0.6220, 0.6507, 0.7506],
        [0.6869, 0.3292, 0.2068],
        [0.2299, 0.2886, 0.1598]])

In [36]:
#element wise mult
tensor*tensor

tensor([[ 1,  4],
        [ 9, 16]])

In [37]:
tensor.mul(tensor)

tensor([[ 1,  4],
        [ 9, 16]])

In [39]:
tensor.sum().item()

10

In [40]:
tensor.add_(5)

tensor([[6, 7],
        [8, 9]])

In [41]:
tensor

tensor([[6, 7],
        [8, 9]])